project:
  type: website
  output-dir: docs
execute:
  freeze: auto
website:
  title: "Creation Care Task Force"
  favicon: "images/favicon.ico"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Core Areas"
        menu:
          - mitigation.qmd
          - adaptation.qmd
          - formation.qmd
          - Process_guidance.qmd
      - text: "Resilience Guides"
        menu:
          - basics.qmd
          - heat.qmd
          - cold.qmd
          - flooding-drainage.qmd
          - wind.qmd
          - hail.qmd
          - wildfire-smoke.qmd
          - power-outages.qmd
          - lightning.qmd
      - text: "Technical Tools"
        menu:
          - energy-audit.qmd
          - water-audit.qmd
          - waste-audit.qmd
          - toilets-faucets.qmd
          - DIY-smoke-scrubber.qmd
          - landscaping.qmd
          - sustainable-hospitality.qmd
          - sandbag-technique.qmd
          - PACE.qmd
      - href: stories.qmd
        text: Stories
      - href: liturgy-for-planting.qmd
        text: Liturgy
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: true # Optional: shows an icon next to external links

editor: source
