---
title: "Book List"
format: html
---

## Indigenous Peoples viewpoint

**Sand Talk: How Indigenous Thinking Can Save the World** *Tyson Yunkaporta*

As an indigenous person, Tyson Yunkaporta looks at global systems from a unique perspective, one tied to the natural and spiritual world. In considering how contemporary life diverges from the pattern of creation, he raises important questions. How does this affect us? How can we do things differently? 

In this thoughtful, culturally rich, mind-expanding book, he provides answers. Yunkaporta’s writing process begins with images. Honoring indigenous traditions, he makes carvings of what he wants to say, channeling his thoughts through symbols and diagrams rather than words. He yarns with people, looking for ways to connect images and stories with place and relationship to create a coherent worldview, and he uses sand talk, the Aboriginal custom of drawing images on the ground to convey knowledge. 

**\* Braiding Sweetgrass: Indigenous Wisdom, Scientific Knowledge and the Teachings of Plants** *Robin Wall Kimmerer*

Drawing on her life as an indigenous scientist, and as a woman, Kimmerer shows how other living beings—asters and goldenrod, strawberries and squash, salamanders, algae, and sweetgrass—offer us gifts and lessons, even if we've forgotten how to hear their voices. In reflections that range from the creation of Turtle Island to the forces that threaten its flourishing today, she circles toward a central argument: that the awakening of ecological consciousness requires the acknowledgment and celebration of our reciprocal relationship with the rest of the living world. For only when we can hear the languages of other beings will we be capable of understanding the generosity of the earth, and learn to give our own gifts in return. 

‘In the Western tradition there is a recognized hierarchy of beings, with, of course, the human being on top—the pinnacle of evolution, the darling of Creation—and the plants at the bottom. But in Native ways of knowing, human people are often referred to as “the younger brothers of Creation.” We say that humans have the least experience with how to live and thus the most to learn—we must look to our teachers among the other species for guidance. Their wisdom is apparent in the way that they live. They teach us by example.’ 

‘How, in our modern world, can we find our way to understand the earth as a gift again, to make our relations with the world sacred again? I know we cannot all become hunter-gatherers—the living world could not bear our weight—but even in a market economy, can we behave “as if ” the living world were a gift?’ 

**The Serviceberry: Abundance and Reciprocity in the Natural World** *Robin Wall Kimmerer and John Burgoyne*

As Indigenous scientist and author of Braiding Sweetgrass Robin Wall Kimmerer harvests serviceberries alongside the birds, she considers the ethic of reciprocity that lies at the heart of the gift economy. How, she asks, can we learn from Indigenous wisdom and the plant world to reimagine what we value most? Our economy is rooted in scarcity, competition, and the hoarding of resources, and we have surrendered our values to a system that actively harms what we love. Meanwhile, the serviceberry’s relationship with the natural world is an embodiment of reciprocity, interconnectedness, and gratitude. The tree distributes its wealth—its abundance of sweet, juicy berries—to meet the needs of its natural community. And this distribution ensures its own survival. As Kimmerer explains, “Serviceberries show us another model, one based upon reciprocity, where wealth comes from the quality of your relationships, not from the illusion of self-sufficiency.” 

## Exploring Other creatures

**Other Minds: The Octopus, the Sea, and the Deep Origins of Consciousness** *Peter Godfrey-Smith*

Although mammals and birds are widely regarded as the smartest creatures on earth, it has lately become clear that a very distant branch of the tree of life has also sprouted higher intelligence: the cephalopods, consisting of the squid, the cuttlefish, and above all the octopus. In captivity, octopuses have been known to identify individual human keepers, raid neighboring tanks for food, turn off light bulbs by spouting jets of water, plug drains, and make daring escapes. How is it that a creature with such gifts evolved through an evolutionary lineage so radically distant from our own? What does it mean that evolution built minds not once but at least twice? The octopus is the closest we will come to meeting an intelligent alien. What can we learn from the encounter? 

**The Reign of Wolf 21: The Saga of Yellowstone’s Legendary Druid Pack (The Alpha Wolves of Yellowstone Book 2)** *Rick McIntyre and Marc Bekoff*

In this compelling follow-up to the national bestseller The Rise of Wolf 8, Rick McIntyre profiles one of Yellowstone’s most revered alpha males, Wolf 21. Leader of the Druid Peak Pack, Wolf 21 was known for his unwavering bravery, his unusual benevolence (unlike other alphas, he never killed defeated rival males), and his fierce commitment to his mate, the formidable Wolf 42. 

Wolf 21 and Wolf 42 were attracted to each other the moment they met—but Wolf 42’s jealous sister interfered viciously in their relationship. After an explosive insurrection within the pack, the two wolves came together at last as leaders of the Druid Peak Pack, which dominated the park for more than 10 years. 

**Finding the Mother Tree: Discovering the Wisdom of the Forest** *Suzanne Simard*

Suzanne Simard is a pioneer on the frontier of plant communication and intelligence; her TED talks have been viewed by more than 10 million people worldwide. 

In this, her first book, now available in paperback, Simard brings us into her world, the intimate world of the trees, in which she brilliantly illuminates the fascinating and vital truths--that trees are not simply the source of timber or pulp, but are a complicated, interdependent circle of life; that forests are social, cooperative creatures connected through underground networks by which trees communicate their vitality and vulnerabilities with communal lives not that different from our own. 

‘The older trees are able to discern which seedlings are their own kin. The old trees nurture the young ones and provide them food and water just as we do with our own children.’ 

**\* Entangled Life: How Fungi Make Our Worlds, Change Our Minds & Shape Our Futures** *Merlin Sheldrake*

When we think of fungi, we likely think of mushrooms. But mushrooms are only fruiting bodies, analogous to apples on a tree. Most fungi live out of sight, yet make up a massively diverse kingdom of organisms that supports and sustains nearly all living systems. Fungi provide a key to understanding the planet on which we live, and the ways we think, feel, and behave. 

Fungi throw our concepts of individuality and even intelligence into question. They are metabolic masters, earth makers, and key players in most of life’s processes. They can change our minds, heal our bodies, and even help us remediate environmental disaster. By examining fungi on their own terms, Sheldrake reveals how these extraordinary organisms—and our relationships with them—are changing our understanding of how life works. 

**Meet the Neighbors: Animal Minds and Life in a More-than-Human World** *Brandon Keim*

Honeybees deliberate democratically. Rats reflect on the past. Snakes have friends. In recent decades, our understanding of animal cognition has exploded, making it indisputably clear that the cities and landscapes around us are filled with thinking, feeling individuals besides ourselves. But the way we relate to wild animals has yet to catch up. In Meet the Neighbors, acclaimed science journalist Brandon Keim asks: what would it mean to take the minds of other animals seriously? 

**Night Magic: Adventures Among Glowworms, Moon Gardens, and Other Marvels of the Dark** *Leigh Ann Henion*

In this glorious celebration of the night, New York Times bestselling nature writer Leigh Ann Henion invites us to leave our well-lit homes, step outside, and embrace the dark as a profoundly beautiful part of the world we inhabit. Because no matter where we live, we are surrounded by animals that rise with the moon, and blooms that reveal themselves as light fades. Henion explores her home region of Appalachia, where she attends a synchronous firefly event in Tennessee, a bat outing in Alabama, and a moth festival in Ohio. In North Carolina, she finds forests alight with bioluminescent mushrooms, neighborhood trees full of screech owls, and valleys teeming with migratory salamanders. Along the way, Henion encounters naturalists, biologists, primitive-skills experts, and others who’ve dedicated their lives to cultivating relationships with darkness. 

## Fiction

**\* The Overstory: A Novel** *Richard Powers*

The Overstory, winner of the 2019 Pulitzer Prize in Fiction, is a sweeping, impassioned work of activism and resistance that is also a stunning evocation of—and paean to—the natural world. From the roots to the crown and back to the seeds, Richard Powers’s twelfth novel unfolds in concentric rings of interlocking fables that range from antebellum New York to the late twentieth-century Timber Wars of the Pacific Northwest and beyond. There is a world alongside ours—vast, slow, interconnected, resourceful, magnificently inventive, and almost invisible to us. This is the story of a handful of people who learn how to see that world and who are drawn up into its unfolding catastrophe. 

**\* The Mountain in the Sea: A Novel** *Ray Nayler*

Humankind discovers intelligent life in an octopus species with its own language and culture, and sets off a high-stakes global competition to dominate the future. 

The transnational tech corporation DIANIMA has sealed off the remote Con Dao Archipelago, where a species of octopus has been discovered that may have developed its own language and culture. The marine biologist Dr. Ha Nguyen, who has spent her life researching cephalopod intelligence, will do anything for the chance to study them. She travels to the islands to join DIANIMA’s team: a battle-scarred security agent and the world’s first (and possibly last) android. 

**Flight Behavior** *Barbara Kingsolver*

Flight Behavior is a brilliant and suspenseful novel set in present day Appalachia; a breathtaking parable of catastrophe and denial that explores how the complexities we inevitably encounter in life lead us to believe in our particular chosen truths. Kingsolver's riveting story concerns a young wife and mother on a failing farm in rural Tennessee who experiences something she cannot explain, and how her discovery energizes various competing factions—religious leaders, climate scientists, environmentalists, politicians—trapping her in the center of the conflict and ultimately opening up her world. Flight Behavior represents contemporary American fiction at its finest. 

## Theology

**\* Creation and the Cross: The Mercy of God for a Planet in Peril** *Elizabeth A. Johnson*

In this fresh creative approach to theology, Elizabeth Johnson asks how we can understand cosmic redemption in a time of advancing ecological devastation. In effect, how can we extend the core Christian belief in salvation to include all created beings. Immediately this quest runs into a formidable obstacle: the idea that Jesus’ death on the cross was required as an atonement for human sin—a theology laid out by the eleventh-century theologian Anselm. Constructing her argument (like Anselm) in the form of a dialogue, Johnson lays out the foundations in scripture, the teachings of Jesus, and the early Church for an understanding that emphasizes the love and mercy of God, showing how this approach could help us respond to a planet in peril. 

“It’s instructive to notice that we humans do not even rate a day of our own, but have to share the sixth day with cattle, creeping things, and wild animals of every kind.” 

“A communal vision permeates the Bible. One particularly lovely text in Job advises people to ask the beasts, birds, plants, and fish to teach us the true nature of things. They will reveal that the life of every living thing as well as the breath of every human being is in God’s hands (Job 12:7–10). Clara. It’s an interesting move, to think the animals and plants can teach us something about God. It’s like accessing the theological witness of the world.” 

“This becomes particularly important when we see that not only did Greek philosophy elevate spirit and denigrate matter, but using those ideas it made the cosmos into one great hierarchy of being. At the lowest level lies inanimate substances like rocks, simply matter. Plants rank next up the ladder since they enjoy a certain spirit of life. Animals are higher yet, because the matter of their body is animated by a greater spirit that gives them locomotion and instincts. Humans with powers of soul including intelligence and free will rank highest on earth. Above humans rank the angels, who are pure spirits without any bodies at all.” 

**\* Sacred Nature: Restoring Our Ancient Bond with the Natural World** *Karen Armstrong*

Since the beginning of time, humankind has looked upon nature and seen the divine. In the writings of the great thinkers across religions, the natural world inspires everything from fear, to awe, to tranquil contemplation; God, or however one defined the sublime, was present in everything. Yet today, even as we admire a tree or take in a striking landscape, we rarely see nature as sacred. 

In this short but deeply powerful book, the best-selling historian of religion Karen Armstrong re-sacralizes nature for modern times. Drawing on her vast knowledge of the world’s religious traditions, she vividly describes nature’s central place in spirituality across the centuries. In bringing this age-old wisdom to life, Armstrong shows modern readers how to rediscover nature’s potency and form a connection to something greater than ourselves. 

**Making Sense of Evolution: Darwin, God, and the Drama of Life** *John F. Haught*

Evolution makes good scientific sense. The question is whether it makes good theological sense as well. Christians who find evolution contrary to faith often do so because they focus solely on the issues of the world's design and the notion of the gradual descent of all life from a common ancestry. But that point of view overlooks the significance of the dramatic narrative going on beneath the surface. What evolution is has become more important than what it means. Haught suggests that, rather than necessarily contradicting one another, theologians and Darwinian scientists actually share an appreciation of the underlying meaning and awe-inspiring mystery of evolution. 

“Theologians, Tillich would insist, should express gratitude to Darwin for bringing to our attention the fact that the idea of special creation is not needed to explain living complexity and diversity. God is not a tinkerer, designer, or first mover. God is the depth, abyss, and ground of all life and all being. As such, God relates to nature and the drama of life in a much more intimate and foundational way than through occasional interference.” 

**Laudato Si: On Care for Our Common Home** *Pope Francis and Catholic Church*

“In the heart of this world, the Lord of life, who loves us so much, is always
present. He does not abandon us, he does not leave us alone, for he has united
himself definitively to our earth, and his love constantly impels us to find new
ways forward. Praise be to him!” – Pope Francis, Laudato Si' In his second
encyclical,Laudato Si': On the Care of Our Common Home, Pope Francis draws all
Christians into a dialogue with every person on the planet about our common
home. We as human beings are united by the concern for our planet, and every
living thing that dwells on it, especially the poorest and most vulnerable. Pope
Francis' letter joins the body of the Church's social and moral teaching, draws
on the best scientific research, providing the foundation for “the ethical and
spiritual itinerary that follows.” Laudato Si'outlines: --The current state of
our “common home” --The Gospel message as seen through creation --The human
causes of the ecological crisis --Ecology and the common good Pope Francis' call
to action for each of us--- Our Sunday Visitor has included discussion
questions, making it perfect for individual or group study, leading all
Catholics and Christians into a deeper understanding of the importance of this
teaching.

## Ecology, Environmentalism

**\* What If We Get It Right?: Visions of Climate Futures** *Ayana Elizabeth Johnson*

Sometimes the bravest thing we can do while facing an existential crisis is imagine life on the other side. This provocative and joyous book maps an inspiring landscape of possible climate futures. 

Through clear-eyed essays and vibrant conversations, infused with data, poetry, and art, Ayana Elizabeth Johnson guides us through solutions and possibilities at the nexus of science, policy, culture, and justice. Visionary farmers and financiers, architects and advocates, help us conjure a flourishing future, one worth the effort it will take—from every one of us, with whatever we have to offer—to create. 

If you haven’t yet been able to picture a transformed and replenished world—or to see yourself, your loved ones, and your community in it—this book is for you. If you haven’t yet found your role in shaping this new world or you’re not sure how we can actually get there, this book is for you. 

With grace, humor, and humanity, Johnson invites readers to ask and answer this ultimate question together: What if we get it right? 

**\* Active Hope (revised): How to Face the Mess We’re in with Unexpected Resilience and Creative Power** *Joanna Macy and Chris Johnstone*

The challenges we face can be difficult even to think about. Climate change, war, political polarization, economic upheaval, and the dying back of nature together create a planetary emergency of overwhelming proportions. This revised, tenth anniversary edition of Active Hope shows us how to strengthen our capacity to face these crises so that we can respond with unexpected resilience and creative power. Drawing on decades of teaching an empowerment approach known as the Work That Reconnects, the authors guide us through a transformational process informed by mythic journeys, modern psychology, spirituality, and holistic science. This process equips us with tools to face the mess we’re in and play our role in the collective transition, or Great Turning, to a life-sustaining society. 

“Active Hope is about becoming active participants in the process of moving toward our hopes and, where we can, realizing them.” 

“Since Active Hope doesn’t require our optimism, we can apply it even in areas where we feel hopeless. The guiding impetus is intention; we choose what we aim to bring about, act for, or express. Rather than weighing our chances and proceeding only when we feel hopeful, we focus on our intention and let it be our guide.” 

**\* Human Nature: Nine Ways to Feel About Our Changing Planet – A Scientist's Hopeful, Heartbreaking Exploration of Climate** *Kate Marvel*

Scientist Kate Marvel has seen the world end before, sometimes several times a day. In the computer models she uses to study climate change, it’s easy to simulate rising temperatures, catastrophic outcomes, and bleak futures. But climate change isn’t just happening in those models. It’s happening here, to the only good planet in the universe. It’s happening to us. And she has feelings about that. 

“We scientists are among the luckiest creatures on Earth; we are allowed to know. Like Cassandra, we see. But the point is not just that Cassandra was ignored. It’s that she was right.” 

“The jet streams exist because hot air rises at the equator and moves toward the cold poles. When the Arctic warms disproportionately, as is happening now, the fuel for this engine sputters, and air moves more sluggishly. This means that weather systems can persist for longer, especially in summer, when the Arctic is losing the most ice. Heat domes that form under suffocatingly high pressures can now linger for weeks or even months before the weather turns.” 

“Sea level rise doesn’t frighten people as much as it should—probably because it seems so gradual, like a slow zombie that can easily be outrun. But the seas will win in the end. Because of the depth of the ocean, because it’s so slow to change, further sea level rise is now inevitable regardless of what humans do. If we stopped emitting greenhouse gases tomorrow, global warming would stop, but Earth would continue to change. Seas would continue to rise. The waters would continue to expand, the ice continue to melt. It now seems all but inevitable that the West Antarctic Ice Sheet is doomed to collapse, pushing sea levels still higher. This is not an argument against reducing emissions to zero; the locked-in sea level rise will only increase further as the temperature does. But we would do well to prepare for the terror we know is coming.” 

**\* Devotions: A Read with Jenna Pick: The Selected Poems of Mary Oliver** *Mary Oliver*

“LITTLE DOGS RHAPSODY IN THE NIGHT

(PERCY THREE)

He puts his cheek against mine
and makes small, expressive sounds.
And when I'm awake, or awake enough

he turns upside down, his four paws
in the air
and his eyes dark and fervent.

Tell me you love me, he says.

Tell me again.

Could there be a sweeter arrangement?
Over and over
he gets to ask it.
I get to tell. 

**The Song of the Dodo: Island Biogeography in an Age of Extinctions** *David Quammen*

Through personal observation, scientific theory, and history, David Quammen examines the mysteries of evolution and extinction and radically alters our understanding of the natural world and our place within it. 

In this landmark of science writing, we learn how the isolation of islands makes them natural laboratories of evolutionary extravagance, as seen in the dragons of Komodo, the elephant birds of Madagascar, the giant tortoises of the Galapagos. But the dark message of island studies is that isolated ecosystems, whether natural or human-made, are also hotbeds of extinction. 

**The Givenness of Things: Essays** *Marilynne Robinson*

The spirit of our times can appear to be one of joyless urgency. As a culture we have become less interested in the exploration of the glorious mind, and more interested in creating and mastering technologies that will yield material well-being. But while cultural pessimism is always fashionable, there is still much to give us hope. In The Givenness of Things, the incomparable Marilynne Robinson delivers an impassioned critique of our contemporary society while arguing that reverence must be given to who we are and what we are: creatures of singular interest and value, despite our errors and depredations. 

**Developing Ecological Consciousness: Becoming Fully Human** *Christopher Uhl*

Teachers and students can trust this remarkably wise, multifaceted, and stimulating book to guide them on a journey from head to heart. This is a book for those who not only want to understand the facts and the science of the ecological crisis but also crave the emotional, philosophical, and spiritual tools to make the personal and societal changes that our planet requires. 

‘For better or worse, stories shape our beliefs, our worldview, and ultimately, our well-being. Some people alive today live in a story that implies that we live in a universe that is indifferent, remote, dead, cold, and lacking in meaning and vitality. Caught in this story, it is possible to conclude that in the big picture, our existence as humans is pretty much a pointless accident and our best strategy, while we are alive, is to seek comfort any way we can. The upshot of this dead universe story, as educator Duane Elgin points out, is “a tendency toward materialism, hedonism and the exploitation of nature.” ’ 

**\* Saving Us: A Climate Scientist's Case for Hope and Healing in a Divided World** *by Katharine Hayhoe*

In Saving Us, Hayhoe argues that when it comes to changing hearts and minds, facts are only one part of the equation. We need to find shared values in order to connect our unique identities to collective action. This is not another doomsday narrative about a planet on fire. It is a multilayered look at science, faith, and human psychology, from an icon in her field—recently named chief scientist at The Nature Conservancy. 

**Fire Weather: On the Front Lines of a Burning World** *John Vaillant*

In May 2016, Fort McMurray, the hub of Canada’s oil industry and America’s biggest foreign supplier, was overrun by wildfire. The multi-billion-dollar disaster melted vehicles, turned entire neighborhoods into firebombs, and drove 88,000 people from their homes in a single afternoon. Through the lens of this apocalyptic conflagration—the wildfire equivalent of Hurricane Katrina—John Vaillant warns that this was not a unique event, but a shocking preview of what we must prepare for in a hotter, more flammable world. 

**On the Move: The Overheating Earth and the Uprooting of America** *Abrahm Lustgarten*

Humanity is on the precipice of a great climate migration, and Americans will not be spared. Tens of millions of people are likely to be driven from the places they call home. Poorer communities will be left behind, while growth will surge in the cities and regions most attractive to climate refugees. America will be changed utterly. 

Abrahm Lustgarten’s On the Move is the definitive account of what this massive population shift might look like. As he shows, the United States will be rendered unrecognizable by four unstoppable forces: wildfires in the West; frequent flooding in coastal regions; extreme heat and humidity in the South; and droughts that will make farming all but impossible across much of the nation. 

**\* Personal top picks**
