---
title: "From Vision to Action"
title-block-banner: images/Label2.png
---

## The Creation Care and Sustainable Church Task Force

Building on the foundation laid by the 2022–2024 [Creation Care Task
Force](https://www.epicenter.org/wp-content/uploads/2025/07/176th-Annual-Council-Journal-Volume-II.pdf#page=107),
a new team was commissioned in September 2025 to turn recommendations into
reality. Our mission is to provide congregations with practical tools and
theological grounding needed to lead in a changing world.

Preparation is about more than just technical steps. We invite you to explore
these real-world [stories](stories.qmd) from throughout our diocese,
highlighting how others are putting resilience into practice, allowing us to
better relate to our fellow travelers and their experiences. Additionally, if
you have a story to share, please contact us. We want to help spread stories of
both successes and failures to all our congregations.


We focus our efforts in three vital areas: **Mitigation**, **Adaptation**, 
and **Formation**.

### [Mitigation](mitigation.html)
**Lowering our impact.** Mitigation is about slowing the progress of climate
change by shrinking our environmental footprint. This includes practical steps
to lower energy consumption, conserve water, and move toward zero-waste
communities.

&nbsp;&nbsp;&nbsp;&nbsp;*Goal: To be better stewards of the resources we use daily.*

### [Adaptation](adaptation.html)
**Building resilience.** While we work to slow climate change, we must also
prepare for its effects. Adaptation involves taking proactive measures to reduce
our vulnerability to climate-related challenges and ensuring our congregations
remain safe, prepared, and resilient.

&nbsp;&nbsp;&nbsp;&nbsp;*Goal: To protect our people and our properties in a shifting climate.*

### [Formation](formation.html)
**Re-imagining our relationship with Earth.** Meaningful change involves
emotion, thought, and action. We seek to engage all three as our community
consciously considers our relationship with all of God’s Creation, moving away
from a mindset of domination and toward acts of loving and responsible
stewardship.

&nbsp;&nbsp;&nbsp;&nbsp;*Goal: To honor the Creator by loving and protecting every aspect of God’s creation.*

***

**Resource Links**

* [Zero Waste Church](https://www.zerowastechurch.org/): A North Carolina
Episcopal Church with a website filled with potential projects for reducing
waste.
* [Keep Texas Beautiful](https://ktb.org/): An organization dedicated to litter
cleanup, with guides for group activities and other resources.

*For more information, contact [Alan Jackson](mailto:alankjackson@gmail.com) and 
[Robin Bullington](robinlbphdpc@gmail.com).*
